export const AccountType = {
  SAVING_ACCOUNT: "SAVING_ACCOUNT",
  CURRENT_ACCOUNT: "CURRENT_ACCOUNT",
  FIXED_SAVING_ACCOUNT: "FIXED_SAVING_ACCOUNT",
};

export const AccountStatus = {
  ACTIVE: "ACTIVE",
  DORMANT: "DORMANT",
  FROZEN: "FROZEN",
  UNDER_REVIEW: "UNDER_REVIEW",
};
